on:
  push:
    branches:
      - develop

name: Deploy PCC Puppet Enforcer DEV

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install n
        run: sudo npm install -g n

      - name: install 16.14.1
        run: sudo n 16.14.1

      - name: Install dependencies
        run: npm install

      - name: Install NestJS globally
        run: npm install -g @nestjs/cli

      - name: Build Project
        run: npm run build && tsc && npm install --production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Prune node_modules
        id: injection
        run: |
          curl -sf https://gobinaries.com/tj/node-prune | sh
          npm run install:prod && npm run prune_me
          mv node_modules/ dist/
          zip -qq -r ./bundle.zip ./dist

      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: pcc-puppet-enforcer
          zip_file: bundle.zip

      - name: Slack Notify
        if: always()
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_USERNAME: PCC-CICD
          SLACK_ICON_EMOJI: ':bell:'
          SLACK_COLOR: ${{ job.status }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

